
  CREATE TABLE "DIM_TIPO_PAGAMENTO" 
   (	"CD_TIPO_PAGAMENTO" NUMBER(5,0), 
	"TIPO_PAGAMENTO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;

  CREATE OR REPLACE TRIGGER "DIM_TIPO_PAGAMENTO_SEQ" 
BEFORE INSERT ON DIM_TIPO_PAGAMENTO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CD_TIPO_PAGAMENTO IS NULL THEN
      SELECT DIM_TIPO_PAGAMENTO_SEQ.NEXTVAL INTO :NEW.CD_TIPO_PAGAMENTO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DIM_TIPO_PAGAMENTO_SEQ" ENABLE;
