
  CREATE TABLE "DIM_VEICULO" 
   (	"CD_VEICULO" NUMBER NOT NULL ENABLE, 
	"VEICULO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "DIM_VEICULO_PK" PRIMARY KEY ("CD_VEICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;

  CREATE OR REPLACE TRIGGER "DIM_VEICULO_SEQ" 
BEFORE INSERT ON DIM_VEICULO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CD_VEICULO IS NULL THEN
      SELECT DIM_VEICULO_SEQ.NEXTVAL INTO :NEW.CD_VEICULO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DIM_VEICULO_SEQ" ENABLE;
