  CREATE TABLE "FATO_LOC" 
   (	"CD_CLIENTE" NUMBER(5,0), 
	"VALOR_TOTAL" NUMBER(13,2) NOT NULL ENABLE, 
	"MEDIA_DIAS_LOCADO" NUMBER(13,1) NOT NULL ENABLE, 
	"MEDIA_DIAS_OCIOSO" NUMBER(13,1) NOT NULL ENABLE, 
	"CD_STATUS" NUMBER(5,0), 
	"CD_TIPO_PAGAMENTO" NUMBER(5,0), 
	"CD_VEICULO" NUMBER(5,0), 
	"DAY_ID" DATE NOT NULL ENABLE
   ) 